# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build web app
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
          cp -r ./dist/* ../server-tcp/public
      - name: run server
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
        working-directory: ./server-tcp
        env:
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          PORT_HTTP: ${{vars.PORT_HTTP}}
          DB_USER: ${{vars.DB_USER}}
          PORT_TCP: ${{vars.PORT_TCP}}
          DB_PORT: ${{vars.DB_PORT}}
          DB_NAME: ${{secrets.DB_NAME}}
        run: |
          echo "
          PORT_TCP = $PORT_TCP 
          PORT_HTTP = $PORT_HTTP
          DB_USER = '$DB_USER'
          DB_PASSWORD = '$DB_PASSWORD'
          DB_HOST = '$DB_HOST'
          DB_NAME = '$DB_NAME'
          DB_PORT = $DB_PORT " > .env
          bun i
          bun install pg-hstore
          bun build ./server.js --compile --outfile mycli
