# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalacion Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Instalacion Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: build web app
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
          cp -r ./dist/* ../server-tcp/public
      - name: build server
        working-directory: ./server-tcp
        run: |
          bun i
          bun install pg-hstore
          bun build ./server.js --compile --outfile mycli
